#
# common makefile for Underworld Adventures Debugger
#
# $Id$
#

libuadebug_la_SOURCES = \
	dbgcommon.hpp pch.cpp \
	dbgapp.hpp dbgapp.cpp \
	mainframe.hpp mainframe.cpp \
	playerinfo.hpp playerinfo.cpp
