#
# common makefile for Underworld Adventures Debugger
#
# $Id$
#

libuadebug_la_SOURCES = \
	dbgcommon.hpp pch.cpp \
	dbgapp.hpp dbgapp.cpp \
	editlist.hpp editlist.cpp \
	mainframe.hpp mainframe.cpp \
	playerinfo.hpp playerinfo.cpp \
	objectlist.hpp objectlist.cpp \
	hotspotlist.hpp hotspotlist.cpp \
	luasrcframe.hpp luasrcframe.cpp \
	tilemapview.hpp tilemapview.cpp
