#
# common makefile for uadata resources
#
# $Id$
#

luaSCRIPTS = \
	uw1/scripts/cutscene.lua \
	uw1/scripts/createchar.lua \
	uw1/scripts/inventory.lua \
	uw1/scripts/objlist.lua \
	uw1/scripts/uwinterface.lua \
	uw1/scripts/game.lua

luaOBJECTS = $(luaSCRIPTS:.lua=.lob)
uarFILES = $(luaOBJECTS) \
	uw1/scripts/uwinit.txt \
	uw1/audio/music.m3u \
	uw1/keymap.cfg

