.\" Underworld Adventures man page for ua-lowercase-all.pl, section 6
.\" $Id$
.\" 
.TH "ua-lowercase-all.pl" 6
.SH NAME
ua-lowercase-all.pl \- script to convert Ultima Underworld file and folder names to lowercase
.SH SYNOPSIS
.B ua-lowercase-all.pl
.I <path-to-underworld-files>
.SH DESCRIPTION
.B ua-lowercase-all.pl
is a tool to automatically convert all file and folder names of an Ultima Underworld installation (that e.g. was made using MS-DOS or Windows and mounted on a Linux system) to lowercase. The Underworld Adventures program
.B uwadv (6)
expects all original game files in lowercase, so this conversion must take place to correctly run the game.
.SH DIAGNOSTICS
The converted file names are printed to the standard output.
.SH BUGS
No bugs are known.
.SH AUTHORS
Cuneyt Cuneyitoglu (Perl Script)
.br
Michael Fink <vividos at sourceforge dot net> (man page)
.SH NOTES
Underworld Adventures is available from the Underworld Adventures home page, at
.I http://uwadv.sourceforge.net/
.SH "SEE ALSO"
.B "uwadv (6)"
