<h2>project downloads</h2>

<p>
Welcome to the download section. Version numbers are boring, and because of this Underworld Adventure releases are named after food, beverages or other silly words people suggest. So expect funny download file names :-) More (and older) files can be found in the Sourceforge <a href="http://sourceforge.net/project/showfiles.php?group_id=50987">Project Files</a>.
</p>

<p>
For the binaries to run, you either need the full version of Ultima Underworld 1 (still available at ebay, etc.) or the Underworld Demo installed on your hard drive. The demo can be freely downloaded at
<a href="http://www.stygianabyss.com/uw/decomorono/" target="_blank">StygianAbyss.com</a> or the <a href="http://www.uo.com/archive/uw1/demoftp.html" target="_blank">Ultima World Wide Web Archive</a>. Please don't ask project team members for a copy of the original.
</p>

<p>
The Underworld Adventures Team is always eager to get feedback for the Underworld Adventures builds that can be downloaded, be it bug reports, suggestions or comments. Just drop a mail to:<?php insert_mail(); ?>. Please add "[uwadv]" or something similar to your mail subject. Or report your bug via the SourceForge <a href="https://sourceforge.net/tracker/?group_id=50987&amp;atid=461662">bug tracker</a>.
</p>

<p>
Latest source code is always available via the <a href="http://sourceforge.net/cvs/?group_id=50987">CVS repository</a> (or <a href="http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/uwadv/uwadv/" target="_blank">browse CVS tree</a>). ChangeLog (autogenerated) is <a href="http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/uwadv/uwadv/ChangeLog?rev=HEAD&amp;content-type=text/vnd.viewcvs-markup">here</a>, Changes file is <a href="http://cvs.uwadv.sourceforge.net/cgi-bin/viewcvs.cgi/*checkout*/uwadv/uwadv/docs/Changes?rev=HEAD&amp;content-type=text/plain">here</a>.
</p>


<h3>release 0.9-mojito</h3>

<p>
Released on 2004-04-10
</p>

<ul>
 <li><a href="http://prdownloads.sourceforge.net/uwadv/uwadv-0.9_mojito.tar.gz?download" target="_blank">uwadv-0.9_mojito.tar.gz</a> (source code)</li>
 <li><a href="http://prdownloads.sourceforge.net/uwadv/uwadv-0.9-mojito-win32.exe?download" target="_blank">uwadv-0.9-mojito-win32.exe</a> (win32 installer)</li>
 <li><a href="http://prdownloads.sourceforge.net/uwadv/uwadv-0.9_mojito-1.i386.rpm?download" target="_blank">uwadv-0.9_mojito-1.i386.rpm</a> (Linux binary RPM)</li>
 <li><a href="http://prdownloads.sourceforge.net/uwadv/uwadv-0.9_mojito-1.src.rpm?download" target="_blank">uwadv-0.9_mojito-1.src.rpm</a> (Linux source RPM)</li>
 <!-- li><a href="" target="_blank"></a> (Debian binary package)</li -->
</ul>

<p>
The updated digital music pack is available here:
</p>

<ul>
<li><a href="http://prdownloads.sourceforge.net/uwadv/uwadv-musicpack-2.zip?download" target="_blank">uwadv-musicpack-2.zip</a> (version 2)</li>
</ul>

<p><a name="mingw-compile" id="mingw-compile">
There are some packages that help setting up MinGW compilation:
</a></p>

<ul>
 <li><a href="http://prdownloads.sourceforge.net/uwadv/uwadv-mingw32-source-setup-2.zip?download" target="_blank">needed files to compile Underworld Adventures using MinGW, package version 2</a></li>
 <li><a href="http://prdownloads.sourceforge.net/uwadv/uwadv-mingw32-installer-setup-2.zip?download" target="_blank">needed files to build an installer for Underworld Adventures, package version 2</a></li>
</ul>


<hr size="1" width="80%"/>

<p>
Here is a page with <a href="index.php?page=oldreleases">older releases</a>
</p>
